version: "0.2"
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
import:
  - ./configs/cspell.config.yaml
useGitignore: true
enableGlobDot: true
ignorePaths:
  - .git
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
dictionaries:
  - filetypes
  - fonts
  - softwareTerms
  - custom-dictionary
words: []
