version: "0.2"
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
import:
  - ./configs/cspell.config.yaml
useGitignore: true
enableGlobDot: true
ignorePaths:
  - .git
dictionaries:
  - filetypes
  - fonts
  - softwareTerms
words:
  - cntrl
  - Dongmin
  - dongminyu
  - dotenv
  - elif
  - esac
  - gradlew
  - ktlint
  - mirae
  - mktemp
  - oxipng
  - pbxproj
  - piggon
  - pinact
  - pipefail
  - Podfile
  - ryaml
  - shellcheck
  - shfmt
  - toplevel
  - ttush
  - worktree
